[package]
name = "relay-sim-reth"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
futures = "0.3.31"
jsonrpsee = {  version = "0.25.1", features = ["server", "macros"] }
reth-chain-state = { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3"}
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3", features = ["full", "cli"] }
tracing = "0.1.41"
tokio = {  version = "1.43.0", features = ["full"] }
revm-primitives = { version = "19.0.0", default-features = false }