[package]
name = "relay-sim-reth"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5", featires = ["derive"] }
ethers = "2.0.14"
eyre = "0.6.12"
jsonrpsee = {  version = "0.25.1", features = ["client", "server", "macros"] }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3", features = ["full", "cli"] }
#reth =  { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3" }
#reth-provider =  { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3" }
#reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag="v1.4.3" }
serde = "1.0.218"
tracing = "0.1.41"
tokio = "1.43.0"
rand = "0.9"
revm = { version = "23.1.0", default-features = false }
revm-primitives = { version = "19.0.0", default-features = false }
serde_json = "1.0.140"