reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
max_width = 120
comment_width = 150
wrap_comments = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
